pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  imageName-9: 'prod-cata'
  img-nm-tg-9: 'prod-cata'
  myregistry: 'dagile'
  tag: 'latest'

steps:
- script: |
    cd productcatalogservice
    docker build -f Dockerfile -t $(imageName-9) .
    docker tag $(imageName-9) $(myregistry).azurecr.io/$(img-nm-tg-9):$(tag)
    az login
    az acr login --name $(myregistry)
    docker push $(myregistry).azurecr.io/$(img-nm-tg-9):$(tag)

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/TEST-RESULTS.xml'
    testRunTitle: 'Test results for JavaScript'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
