image:
  repository: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.4
  tag: ""

service:
  name: grpc
  type: ClusterIP
  port: 50051
  targetport: 50051

container: 
  name: server
  containerport: 50051

  extraEnv:
    - name: PORT
      value: "50051"
  # - name: DISABLE_STATS
  #   value: "1"
  # - name: DISABLE_TRACING
  #   value: "1"
  # - name: DISABLE_PROFILER
  #   value: "1"
  # - name: JAEGER_SERVICE_ADDR
  #   value: "jaeger-collector:14268"
  
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi