image:
  repository: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.4
  tag: ""

service:
  name: grpc
  type: ClusterIP
  port: 5050
  targetport: 5050

container: 
  name: server
  containerport: 5050

  extraEnv:
    - name: PORT
      value: "5050"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "productcatalogservice:3550"
    - name: SHIPPING_SERVICE_ADDR
      value: "shippingservice:50051"
    - name: PAYMENT_SERVICE_ADDR
      value: "paymentservice:50051"
    - name: EMAIL_SERVICE_ADDR
      value: "emailservice:5000"
    - name: CURRENCY_SERVICE_ADDR
      value: "currencyservice:7000"
    - name: CART_SERVICE_ADDR
      value: "cartservice:7070"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi