image:
  repository: gcr.io/google-samples/microservices-demo/adservice:v0.2.4
  tag: ""

service:
  name: grpc
  type: ClusterIP
  port: 9555
  targetport: 9555

account:
  servicename: default
  terminationperiod: 5

container: 
  name: server
  containerport: 9555

  extraEnv:
    - name: PORT
      value: "9555"

  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi

rlp:
  initialDelaySeconds: 20
  periodSeconds: 15
