#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master

stages:
- stage: build
  jobs:
  - job: Build_Docker_Image
    pool:
      vmImage: 'Ubuntu 16.04'
  
    variables:
      imageName-1: 'loadgenerator'

    steps:
    - script: |
        cd loadgenerator
        docker build -f Dockerfile -t $(imageName-1) .
        
- stage: deploy
  jobs:
  - job: deploy_helm_chart
    pool:
      vmImage: 'Ubuntu 16.04'
  
    steps:
    - script: |
        cd loadgenerator
        az login
        az aks get-credentials --resource-group Training-rg --name dagile
        kubectl create namespace loadgenerator
        helm install loadgenerator ./helm-chart -n loadgenerator
