#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'
  
stages:
- stage: build
  jobs:
  - job: Build_Docker_Image
    
    variables:
      imageName-1: 'adservice'

    steps:
    - script: |
        cd adservice
        docker login -u "${dockerid}" -p "${dockerpswd}"
        docker build -t "${imageName-1}" .
        
- stage: list 
  jobs:
  - job: list_docker_image 
       
    steps:
    - script: |
        docker images

- stage: scan 
  jobs:
  - job: scan_docker_image
  
    steps:
    - script: |
        cd adservice
#        curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0
#        bash -s -- -f -d Dockerfile adservice
        
    - task: Anchore@0
      inputs:
        image: "${imageName-1}"
        dockerfile: adservice/Dockerfile
        failBuild: true

- stage: deploy
  jobs:
  - job: deploy_helm_chart
  
    steps:
    - script: |
        cd adservice
        az login
        az aks get-credentials --resource-group Training-rg --name dagile
        kubectl create namespace adservice
        helm install adservices ./helm-chart -n adservice


  


