#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master

stages:
- stage: build
  jobs:
  - job: Build_Docker_Image
    pool:
      vmImage: 'Ubuntu 16.04'
  
    variables:
      imageName-1: 'adservice'

    steps:
    - script: |
        cd adservice 
        docker build -f Dockerfile -t localbuild/$(imageName-1) .

- stage: scan 
  jobs:
  - job: scan_docker_image
    pool:
      vmImage: 'Ubuntu 16.04'
  
    steps:
    - script: |
        cd adservice
 #       curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0
 #       bash -s -- -f -d Dockerfile adservice
        
    - task: Anchore@0
      inputs:
        image: 'localbuild/adservice'
        dockerfile: Dockerfile
        failBuild: true

- stage: deploy
  jobs:
  - job: deploy_helm_chart
    pool:
      vmImage: 'Ubuntu 16.04'
  
    steps:
    - script: |
        cd adservice
        az login
        az aks get-credentials --resource-group Training-rg --name dagile
        kubectl create namespace adservice
        helm install adservices ./helm-chart -n adservice


  


