replicaCount: 1

image:
  repository: busybox:latest
  tag: ""

service:
  type: ClusterIP
  port: 80

ic:
  name: frontend-check

  extraEnv:
    - name: FRONTEND_ADDR
      value: "frontend:80"

container:
  name: main
  image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.2.4
  extraEnv:
    - name: FRONTEND_ADDR
      value: "frontend:80"
    - name: USERS
      value: "10"

  resources: 
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
        cpu: 500m
        memory: 512Mi

