#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'
  
stages:
- stage: build
  jobs:
  - job: Build_Docker_Image
    
    variables:
      imageName-1: 'test'

    steps:
    - script: |
        cd checkoutservice
        docker login -u "${dockerid}" -p "${dockerpswd}"
        docker build -t test .
        
- stage: list 
  jobs:
  - job: list_docker_image 
       
    steps:
    - script: |
        docker images
