#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName-3: 'checkoutservice'
  containerRegistry: 'dagile.azurecr.io'
  myregistry: 'dagile'
  tag: 'latest'
  repo: 'online_boutique'

stages:
- stage: build_and_push
  jobs:
  - job: build_and_pull_docker_image_from_dockerhub

    steps:
    - script: |
        docker login -u "${dockerid}" -p "${dockerpswd}"
        docker pull katharinechristine/online_boutique:latest

- stage: list 
  jobs:
  - job: list_docker_image 
       
    steps:
    - script: |
        docker images

- stage: scan 
  jobs:
  - job: scan_docker_image
    steps:
    - script: |
        cd checkoutservice

  - task: Anchore@0
    inputs:
      image: 'katharinechristine/online_boutique:latest'
      dockerfile: checkoutservice/Dockerfile
      failBuild: true
