#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master
- dev

variables:
  image_name: "localbuild/checkoutservice"
  tag: "ci"

stages:
- stage: build_and_scan
  jobs:
  - job: build_and_scan

    steps:
#    - script: |
#        cd checkoutservice
        
    - task: Docker@2
      inputs:
        command: build
        repository: "$(image_name)"
        tags: "$(tag)"

    - task: Anchore@0
      inputs:
        image: "$(image_name):$(tag)"
        dockerfile: Dockerfile
        
    - script: |
        echo $(billOfMaterials)
        echo $(vulnerabilities)
      displayName: Print scan artifacts

    

