#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName-3: 'checkoutservice'
  containerRegistry: 'dagile.azurecr.io'
  myregistry: 'dagile'
  tag: 'latest'
  repo: 'online_boutique'

stages:
- stage: build_and_push
  jobs:
  - job: build_and_pull_docker_image_from_dockerhub

    steps:
    - script: |
        cd checkoutservice
        docker build -t checkoutservice .

- stage: list 
  jobs:
  - job: list_docker_image 
       
    steps:
    - script: |
        docker images

- stage: scan 
  jobs:
  - job: scan_docker_image
    steps:
    - script: |
        curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 
        bash -s -- -f -r checkoutservice


    

