#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master
- dev

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  myregistry: "dagile"
  containerRegistry: "dagile.azurecr.io" 
  imageRepository: "checkoutservice"
  image_name: "checkoutservice"
  tag: "latest"
  releaseName: "checkoutservice"
  nameSpace: "checkoutservice"

stages:
- stage: pull
  jobs:
  - job: pull_image_from_acr

    steps:
    - script: |
        az login
        az acr login --name $(myregistry)
        docker pull $(containerRegistry)/$(imageRepository):$(tag)
        
#    - task: Docker@2
#      inputs:
#        command: build
#        repository: "$(image_name)"
#        tags: "$(tag)"

- stage: Scan
  jobs:
  - job: scan_image

    steps:
    - script: |
        sudo apt-get install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
        sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
        trivy -v
      displayName: 'Download and install Trivy'

    - task: CmdLine@2
      displayName: Scan
      inputs:
        script: |
         trivy image --exit-code 0 --severity LOW,MEDIUM $(containerRegistry)/$(imageRepository):$(tag)
         trivy image --exit-code 1 --severity HIGH,CRITICAL $(containerRegistry)/$(imageRepository):$(tag)
#        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity MEDIUM,HIGH --ignore-unfixed $(containerRegistry)/$(imageRepository):$(tag)
         
#        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 1 --severity CRITICAL --ignore-unfixed $(containerRegistry)/$(imageRepository):$(tag)

# - stage: deploy
#   jobs:
#   - job: deploy_helm_chart
  
#     steps:
#     - script: |
#         cd checkoutservice
#         helm deploy $(releaseName) ./helmchart -n $(nameSpace)
     
    
    

