#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  image_name: 'checkoutservice'
  containerRegistry: 'dagile.azurecr.io'
  myregistry: 'dagile'
  tag: 'latest'
  repo: 'online_boutique'

stages:
- stage: build_and_push
  jobs:
  - job: build_and_pull_docker_image_from_dockerhub

    steps:
    - script: |
        cd checkoutservice
        
    - task: Docker@2
      inputs:
        command: build
        repository: "$(image_name)"
        tags: "$(tag)"

- stage: list 
  jobs:
  - job: list_docker_image 
       
    steps:
    - script: |
        docker images

- stage: scan 
  jobs:
  - job: scan_docker_image

    steps:
    - script: |
        cd checkoutservice

    - task: Anchore@0
      inputs:
        image: "$(image_name):$(tag)"
        customPolicyPath: ".anchore/policy.json"
        dockerfile: Dockerfile
        
    - script: |
        echo $(policyStatus)
        echo $(billOfMaterials)
        cat $(billOfMaterials)
        echo $(vulnerabilities)
        cat $(vulnerabilities)
      displayName: Print scan artifacts

    

