#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master
- dev

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  image_name: "checkoutservice"
  tag: "ci"

stages:
- stage: build_and_scan
  jobs:
  - job: build_and_scan

    steps:
    - script: |
        cd checkoutservice
        /usr/bin/docker build -f /home/vsts/work/1/s/checkoutservice/Dockerfile
        
#    - task: Docker@2
#      inputs:
#        command: build
#        repository: "$(image_name)"
#        tags: "$(tag)"

    - task: Anchore@0
      inputs:
        image: "$(image_name):$(tag)"
        dockerfile: Dockerfile
        
    - script: |
        echo $(billOfMaterials)
        echo $(vulnerabilities)
      displayName: Print scan artifacts

    

