#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName-3: 'checkoutservice'
  tag: 'latest'
  repo: 'online_boutique'

stages:
- stage: build_and_push
  jobs:
  - job: build_and_pull_docker_image_from_dockerhub

    steps:
    - script: |
        cd checkoutservice
        docker build -t checkoutservice .
        docker tag checkoutservice katharinechristine/online_boutique:latest
        docker login -u "${dockerid}" -p "${dockerpswd}"
        docker push katharinechristine/online_boutique:latest

- stage: list 
  jobs:
  - job: list_docker_image 
       
    steps:
    - script: |
        docker images

- stage: scan 
  jobs:
  - job: scan_docker_image
  
    steps:

    - script: |
        docker pull katharinechristine/online_boutique:latest
        docker scan katharinechristine/online_boutique:latest

#        cd checkoutservice
#        curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0
#        bash -s -- -f -r $(img-nm-tg-3):$(tag)
        
#    - task: Anchore@0
#      inputs:
#        image: "${imageName-3}"
#        dockerfile: adservice/Dockerfile
#        failBuild: true
