#Pipeline to depoly helm-chart of the respective MS when the respective image is build
trigger:
- master
- dev

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  myregistry: "dagile"
  containerRegistry: "dagile.azurecr.io" 
  imageRepository: "checkoutservice"
  image_name: "checkoutservice"
  tag: "latest"

stages:
- stage: build_and_scan
  jobs:
  - job: build_and_scan

    steps:
    - script: |
        az login
        az acr login --name $(myregistry)
        docker pull $(containerRegistry)/$(imageRepository):$(tag)
        
#    - task: Docker@2
#      inputs:
#        command: build
#        repository: "$(image_name)"
#        tags: "$(tag)"

    - task: CmdLine@2
      displayName: Scan
      inputs:
        script: |
         docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity MEDIUM,HIGH --ignore-unfixed $(containerRegistry)/$(imageRepository):$(tag)
         
         docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 1 --severity CRITICAL --ignore-unfixed $(containerRegistry)/$(imageRepository):$(tag)
        
    
    

