
image:
  repository: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.4
  tag: ""

service:
  name: grpc
  type: ClusterIP
  port: 7000
  targetport: 7000

account:
  servicename: default
  terminationperiod: 5
    
container: 
  name: server
  containerport: 7000

  extraEnv:
    - name: PORT
      value: "7000"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi