
image:
  repository: gcr.io/google-samples/microservices-demo/emailservice:v0.2.4
  tag: ""

service:
  name: grpc
  type: ClusterIP
  port: 5000
  targetport: 8080

account:
  servicename: default
  terminationperiod: 5

container: 
  name: server
  containerport: 8080

  extraEnv:
    - name: PORT
      value: "8080"
    - name: DISABLE_PROFILER
      value: "1"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

