apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      serviceAccountName: {{ .Values.account.servicename }}
      terminationGracePeriodSeconds: {{ .Values.account.terminationperiod }}
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.container.containerport }}
        env: {{- with .Values.container.extraEnv }}{{ toYaml . | nindent 8 }}{{- end }}
        readinessProbe:
          periodSeconds: {{ .Values.account.terminationperiod }}
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: {{ .Values.account.terminationperiod }}
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources: {{- with .Values.container.resources }}{{ toYaml . | nindent 10 }}{{- end }}
          