apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: recommendationservice
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
